# Generated by Django 5.2 on 2025-12-16 22:00

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_project_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperateus',
            options={'verbose_name': 'درخواست همکاری', 'verbose_name_plural': 'درخواست های همکاری'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cooperateus',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='cooperateus',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='cooperateus',
            name='cv',
            field=models.FileField(upload_to='CV/%Y-%m-%d/', verbose_name='رزومه'),
        ),
        migrations.AlterField(
            model_name='cooperateus',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='cooperateus',
            name='education',
            field=models.CharField(max_length=50, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='cooperateus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='پست الکترونیکی'),
        ),
        migrations.AlterField(
            model_name='cooperateus',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='cooperateus',
            name='gender',
            field=models.CharField(choices=[('مرد', 'Male'), ('زن', 'Female')], max_length=12, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='cooperateus',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='cooperateus',
            name='marital_status',
            field=models.CharField(choices=[('مجرد', 'Single'), ('متاهل', 'Married')], max_length=12, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='cooperateus',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='cooperateus',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='published_date',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
