# Generated by Django 5.2 on 2025-12-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_projectcategory_project_tags_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='counted_views',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
