# Generated by Django 5.2 on 2026-01-31 20:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_project_counted_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا پروژه '),
        ),
    ]
