# Generated by Django 5.2 on 2025-12-16 22:00

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'verbose_name': 'کد یکبار مصرف', 'verbose_name_plural': 'کدهای یکبار مصرف'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('مرد', 'Male'), ('زن', 'Female')], default='مرد', max_length=12, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='User/default.jpg', upload_to='User/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.PositiveSmallIntegerField(verbose_name='کد یکبار مصرف'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=58, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال هست ؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین هست ؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='شماره ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
