# Generated by Django 5.2 on 2026-01-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_birth_date_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('مرد', 'Male'), ('زن', 'Female')], max_length=12, verbose_name='جنسیت'),
        ),
    ]
