# Generated by Django 5.2 on 2025-12-26 21:57

import django.core.validators
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_submitted_at_order_order_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='کد تخفیف')),
                ('valid_from', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع کد')),
                ('valid_to', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان کد')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='مقدار تخفیف')),
                ('active', models.BooleanField(default=False, verbose_name='فعال بودن کد')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='تخفیف سفارش'),
        ),
    ]
