# Generated by Django 5.2 on 2026-01-23 18:40

import django.core.validators
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon_order_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'پرداخت نقدی'), ('installment', 'پرداخت اقساطی (اسنپ\u200cپی)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع اعتبار'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان اعتبار'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('waiting_approval', 'در انتظار تأیید مدیر'), ('approved', 'تأیید شده'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='pending_payment', max_length=20),
        ),
    ]
