# Generated by Django 5.2 on 2026-01-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_coupon_options_order_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'پرداخت نقدی'), ('installment', 'پرداخت اقساطی (اسنپ\u200cپی)')], max_length=20, null=True, verbose_name='نوع پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('waiting_approval', 'در انتظار تأیید مدیر'), ('approved', 'تأیید شده'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='pending_payment', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
