# Generated by Django 5.2 on 2026-01-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_payment_type_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_address', 'در انتظار آدرس'), ('pending_payment', 'در انتظار پرداخت'), ('waiting_approval', 'در انتظار تأیید مدیر'), ('approved', 'تأیید شده'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='pending_address', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
