# Generated by Django 5.2 on 2026-01-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_address', 'در انتظار ثبت آدرس'), ('waiting_payment', 'در انتظار انتخاب روش پرداخت'), ('waiting_approval', 'در انتظار تأیید مدیر'), ('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='waiting_address', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
