# Generated by Django 5.2 on 2025-12-04 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان محصول')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('product_code', models.CharField(unique=True, verbose_name='کد محصول')),
                ('slug', models.SlugField(unique=True)),
                ('product_brand', models.CharField(max_length=200, verbose_name='برند محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('available', models.BooleanField(verbose_name='وضعیت فعال محصول')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Modem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('lan_port', models.IntegerField(verbose_name='تعداد پورت شبکه')),
                ('lan_speed', models.CharField(max_length=50, verbose_name='سرعت پورت شبکه')),
                ('anten_power', models.IntegerField(verbose_name='قدرت آنتن')),
                ('anten_quantity', models.IntegerField(verbose_name='تعداد آنتن')),
                ('tel_quantity', models.IntegerField(verbose_name='تعداد پورت تلفن')),
                ('usb_quantity', models.IntegerField(verbose_name='تعداد پورت USB')),
                ('wifi_technology', models.CharField(max_length=50, verbose_name='تکنولوژی Wifi')),
                ('wifi_speed', models.IntegerField(verbose_name='سرعت وایرلس')),
                ('wifi5_speed', models.IntegerField(verbose_name='سرعت وایرلس باند 5')),
                ('pon', models.CharField(max_length=50, verbose_name='PON')),
                ('two_bands', models.BooleanField(verbose_name='دو بانده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modem', to='products.product')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی های محصول',
                'ordering': ('wifi_technology', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y%m%d/', verbose_name='تصویر محصول')),
                ('alt_text', models.CharField(max_length=200, verbose_name='توضیحات تصویر')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ('-is_primary', 'created_at'),
            },
        ),
    ]
